// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"github.com/khanghh/kauth/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newAuditEvent(db *gorm.DB, opts ...gen.DOOption) auditEvent {
	_auditEvent := auditEvent{}

	_auditEvent.auditEventDo.UseDB(db, opts...)
	_auditEvent.auditEventDo.UseModel(&model.AuditEvent{})

	tableName := _auditEvent.auditEventDo.TableName()
	_auditEvent.ALL = field.NewAsterisk(tableName)
	_auditEvent.ID = field.NewUint64(tableName, "id")
	_auditEvent.UserID = field.NewUint(tableName, "user_id")
	_auditEvent.Username = field.NewString(tableName, "username")
	_auditEvent.EventType = field.NewString(tableName, "event_type")
	_auditEvent.ServiceID = field.NewUint(tableName, "service_id")
	_auditEvent.ServiceName = field.NewString(tableName, "service_name")
	_auditEvent.Success = field.NewBool(tableName, "success")
	_auditEvent.Reason = field.NewString(tableName, "reason")
	_auditEvent.IP = field.NewString(tableName, "ip")
	_auditEvent.UserAgent = field.NewString(tableName, "user_agent")
	_auditEvent.CreatedAt = field.NewTime(tableName, "created_at")

	_auditEvent.fillFieldMap()

	return _auditEvent
}

type auditEvent struct {
	auditEventDo

	ALL         field.Asterisk
	ID          field.Uint64
	UserID      field.Uint
	Username    field.String
	EventType   field.String
	ServiceID   field.Uint
	ServiceName field.String
	Success     field.Bool
	Reason      field.String
	IP          field.String
	UserAgent   field.String
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (a auditEvent) Table(newTableName string) *auditEvent {
	a.auditEventDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a auditEvent) As(alias string) *auditEvent {
	a.auditEventDo.DO = *(a.auditEventDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *auditEvent) updateTableName(table string) *auditEvent {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint64(table, "id")
	a.UserID = field.NewUint(table, "user_id")
	a.Username = field.NewString(table, "username")
	a.EventType = field.NewString(table, "event_type")
	a.ServiceID = field.NewUint(table, "service_id")
	a.ServiceName = field.NewString(table, "service_name")
	a.Success = field.NewBool(table, "success")
	a.Reason = field.NewString(table, "reason")
	a.IP = field.NewString(table, "ip")
	a.UserAgent = field.NewString(table, "user_agent")
	a.CreatedAt = field.NewTime(table, "created_at")

	a.fillFieldMap()

	return a
}

func (a *auditEvent) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *auditEvent) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 11)
	a.fieldMap["id"] = a.ID
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["username"] = a.Username
	a.fieldMap["event_type"] = a.EventType
	a.fieldMap["service_id"] = a.ServiceID
	a.fieldMap["service_name"] = a.ServiceName
	a.fieldMap["success"] = a.Success
	a.fieldMap["reason"] = a.Reason
	a.fieldMap["ip"] = a.IP
	a.fieldMap["user_agent"] = a.UserAgent
	a.fieldMap["created_at"] = a.CreatedAt
}

func (a auditEvent) clone(db *gorm.DB) auditEvent {
	a.auditEventDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a auditEvent) replaceDB(db *gorm.DB) auditEvent {
	a.auditEventDo.ReplaceDB(db)
	return a
}

type auditEventDo struct{ gen.DO }

func (a auditEventDo) Debug() *auditEventDo {
	return a.withDO(a.DO.Debug())
}

func (a auditEventDo) WithContext(ctx context.Context) *auditEventDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a auditEventDo) ReadDB() *auditEventDo {
	return a.Clauses(dbresolver.Read)
}

func (a auditEventDo) WriteDB() *auditEventDo {
	return a.Clauses(dbresolver.Write)
}

func (a auditEventDo) Session(config *gorm.Session) *auditEventDo {
	return a.withDO(a.DO.Session(config))
}

func (a auditEventDo) Clauses(conds ...clause.Expression) *auditEventDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a auditEventDo) Returning(value interface{}, columns ...string) *auditEventDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a auditEventDo) Not(conds ...gen.Condition) *auditEventDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a auditEventDo) Or(conds ...gen.Condition) *auditEventDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a auditEventDo) Select(conds ...field.Expr) *auditEventDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a auditEventDo) Where(conds ...gen.Condition) *auditEventDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a auditEventDo) Order(conds ...field.Expr) *auditEventDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a auditEventDo) Distinct(cols ...field.Expr) *auditEventDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a auditEventDo) Omit(cols ...field.Expr) *auditEventDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a auditEventDo) Join(table schema.Tabler, on ...field.Expr) *auditEventDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a auditEventDo) LeftJoin(table schema.Tabler, on ...field.Expr) *auditEventDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a auditEventDo) RightJoin(table schema.Tabler, on ...field.Expr) *auditEventDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a auditEventDo) Group(cols ...field.Expr) *auditEventDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a auditEventDo) Having(conds ...gen.Condition) *auditEventDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a auditEventDo) Limit(limit int) *auditEventDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a auditEventDo) Offset(offset int) *auditEventDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a auditEventDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *auditEventDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a auditEventDo) Unscoped() *auditEventDo {
	return a.withDO(a.DO.Unscoped())
}

func (a auditEventDo) Create(values ...*model.AuditEvent) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a auditEventDo) CreateInBatches(values []*model.AuditEvent, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a auditEventDo) Save(values ...*model.AuditEvent) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a auditEventDo) First() (*model.AuditEvent, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditEvent), nil
	}
}

func (a auditEventDo) Take() (*model.AuditEvent, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditEvent), nil
	}
}

func (a auditEventDo) Last() (*model.AuditEvent, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditEvent), nil
	}
}

func (a auditEventDo) Find() ([]*model.AuditEvent, error) {
	result, err := a.DO.Find()
	return result.([]*model.AuditEvent), err
}

func (a auditEventDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AuditEvent, err error) {
	buf := make([]*model.AuditEvent, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a auditEventDo) FindInBatches(result *[]*model.AuditEvent, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a auditEventDo) Attrs(attrs ...field.AssignExpr) *auditEventDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a auditEventDo) Assign(attrs ...field.AssignExpr) *auditEventDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a auditEventDo) Joins(fields ...field.RelationField) *auditEventDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a auditEventDo) Preload(fields ...field.RelationField) *auditEventDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a auditEventDo) FirstOrInit() (*model.AuditEvent, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditEvent), nil
	}
}

func (a auditEventDo) FirstOrCreate() (*model.AuditEvent, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AuditEvent), nil
	}
}

func (a auditEventDo) FindByPage(offset int, limit int) (result []*model.AuditEvent, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a auditEventDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a auditEventDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a auditEventDo) Delete(models ...*model.AuditEvent) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *auditEventDo) withDO(do gen.Dao) *auditEventDo {
	a.DO = *do.(*gen.DO)
	return a
}
